import type { Product, Category } from "./types";

// Category information for display
export const categories: { id: Category; name: string; icon: string }[] = [
  { id: "mobiles", name: "Mobiles", icon: "smartphone" },
  { id: "laptops", name: "Laptops", icon: "laptop" },
  { id: "tablets", name: "Tablets", icon: "tablet" },
  { id: "headphones", name: "Headphones", icon: "headphones" },
  { id: "gaming", name: "Gaming", icon: "gamepad-2" },
  { id: "accessories", name: "Accessories", icon: "cable" },
];

// Sample product data
export const products: Product[] = [
  // Mobiles
  {
    id: "m1",
    name: "iPhone 15 Pro Max",
    brand: "Apple",
    category: "mobiles",
    price: 1199,
    originalPrice: 1299,
    discount: 8,
    rating: 4.8,
    reviewCount: 2456,
    image: "https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=400&h=400&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800&h=800&fit=crop",
      "https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?w=800&h=800&fit=crop",
    ],
    description: "The most powerful iPhone ever with A17 Pro chip, titanium design, and advanced camera system.",
    specifications: {
      Display: "6.7-inch Super Retina XDR",
      Chip: "A17 Pro",
      Storage: "256GB",
      Camera: "48MP Main + 12MP Ultra Wide",
      Battery: "Up to 29 hours video playback",
    },
    inStock: true,
    featured: true,
  },
  {
    id: "m2",
    name: "Samsung Galaxy S24 Ultra",
    brand: "Samsung",
    category: "mobiles",
    price: 1099,
    originalPrice: 1199,
    discount: 8,
    rating: 4.7,
    reviewCount: 1823,
    image: "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=400&h=400&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=800&h=800&fit=crop",
    ],
    description: "Ultimate Galaxy experience with Galaxy AI, S Pen, and 200MP camera.",
    specifications: {
      Display: "6.8-inch QHD+ Dynamic AMOLED",
      Processor: "Snapdragon 8 Gen 3",
      Storage: "256GB",
      Camera: "200MP Wide + 12MP Ultra Wide",
      Battery: "5000mAh",
    },
    inStock: true,
    featured: true,
    bestDeal: true,
  },
  {
    id: "m3",
    name: "Google Pixel 8 Pro",
    brand: "Google",
    category: "mobiles",
    price: 899,
    rating: 4.6,
    reviewCount: 1234,
    image: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=400&h=400&fit=crop",
    description: "The best of Google AI in a premium smartphone with incredible camera capabilities.",
    specifications: {
      Display: "6.7-inch LTPO OLED",
      Processor: "Google Tensor G3",
      Storage: "128GB",
      Camera: "50MP Wide + 48MP Ultra Wide",
      Battery: "5050mAh",
    },
    inStock: true,
    featured: true,
  },
  {
    id: "m4",
    name: "OnePlus 12",
    brand: "OnePlus",
    category: "mobiles",
    price: 799,
    originalPrice: 899,
    discount: 11,
    rating: 4.5,
    reviewCount: 987,
    image: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400&h=400&fit=crop",
    description: "Flagship performance with Hasselblad camera and blazing fast charging.",
    specifications: {
      Display: "6.82-inch 2K LTPO AMOLED",
      Processor: "Snapdragon 8 Gen 3",
      Storage: "256GB",
      Camera: "50MP Main Hasselblad",
      Battery: "5400mAh with 100W charging",
    },
    inStock: true,
    bestDeal: true,
  },

  // Laptops
  {
    id: "l1",
    name: 'MacBook Pro 16"',
    brand: "Apple",
    category: "laptops",
    price: 2499,
    rating: 4.9,
    reviewCount: 1567,
    image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=400&h=400&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&h=800&fit=crop",
      "https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=800&h=800&fit=crop",
    ],
    description: "The most powerful MacBook Pro ever with M3 Max chip for demanding workflows.",
    specifications: {
      Display: '16.2" Liquid Retina XDR',
      Chip: "Apple M3 Max",
      Memory: "36GB Unified Memory",
      Storage: "512GB SSD",
      Battery: "Up to 22 hours",
    },
    inStock: true,
    featured: true,
  },
  {
    id: "l2",
    name: "Dell XPS 15",
    brand: "Dell",
    category: "laptops",
    price: 1799,
    originalPrice: 1999,
    discount: 10,
    rating: 4.6,
    reviewCount: 892,
    image: "https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=400&h=400&fit=crop",
    description: "Premium Windows laptop with stunning 4K OLED display and powerful performance.",
    specifications: {
      Display: '15.6" 4K OLED Touch',
      Processor: "Intel Core i9-13900H",
      Memory: "32GB DDR5",
      Storage: "1TB SSD",
      Graphics: "NVIDIA RTX 4060",
    },
    inStock: true,
    bestDeal: true,
  },
  {
    id: "l3",
    name: "ThinkPad X1 Carbon",
    brand: "Lenovo",
    category: "laptops",
    price: 1549,
    rating: 4.7,
    reviewCount: 756,
    image: "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=400&h=400&fit=crop",
    description: "Ultra-light business laptop with legendary ThinkPad reliability.",
    specifications: {
      Display: '14" 2.8K OLED',
      Processor: "Intel Core i7-1365U",
      Memory: "16GB LPDDR5",
      Storage: "512GB SSD",
      Weight: "1.12kg",
    },
    inStock: true,
  },

  // Tablets
  {
    id: "t1",
    name: 'iPad Pro 12.9"',
    brand: "Apple",
    category: "tablets",
    price: 1099,
    rating: 4.8,
    reviewCount: 2134,
    image: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=400&h=400&fit=crop",
    description: "The ultimate iPad experience with M2 chip and stunning Liquid Retina XDR display.",
    specifications: {
      Display: '12.9" Liquid Retina XDR',
      Chip: "Apple M2",
      Storage: "256GB",
      Connectivity: "Wi-Fi 6E + 5G",
      Camera: "12MP Wide + 10MP Ultra Wide",
    },
    inStock: true,
    featured: true,
  },
  {
    id: "t2",
    name: "Samsung Galaxy Tab S9 Ultra",
    brand: "Samsung",
    category: "tablets",
    price: 1199,
    originalPrice: 1399,
    discount: 14,
    rating: 4.6,
    reviewCount: 876,
    image: "https://images.unsplash.com/photo-1561154464-82e9adf32764?w=400&h=400&fit=crop",
    description: "Massive display tablet with S Pen and desktop-class performance.",
    specifications: {
      Display: '14.6" Dynamic AMOLED 2X',
      Processor: "Snapdragon 8 Gen 2",
      Memory: "12GB RAM",
      Storage: "256GB",
      Battery: "11200mAh",
    },
    inStock: true,
    bestDeal: true,
  },
  {
    id: "t3",
    name: "Surface Pro 9",
    brand: "Microsoft",
    category: "tablets",
    price: 999,
    rating: 4.5,
    reviewCount: 654,
    image: "https://images.unsplash.com/photo-1585790050230-5dd28404ccb9?w=400&h=400&fit=crop",
    description: "Versatile 2-in-1 tablet that replaces your laptop.",
    specifications: {
      Display: '13" PixelSense Flow',
      Processor: "Intel Core i7-1255U",
      Memory: "16GB LPDDR5",
      Storage: "256GB SSD",
      Battery: "Up to 15.5 hours",
    },
    inStock: true,
  },

  // Headphones
  {
    id: "h1",
    name: "AirPods Max",
    brand: "Apple",
    category: "headphones",
    price: 549,
    rating: 4.7,
    reviewCount: 3456,
    image: "https://images.unsplash.com/photo-1613040809024-b4ef7ba99bc3?w=400&h=400&fit=crop",
    description: "High-fidelity audio with industry-leading Active Noise Cancellation.",
    specifications: {
      Type: "Over-ear",
      "Noise Cancellation": "Active Noise Cancellation",
      "Spatial Audio": "Yes, with dynamic head tracking",
      Battery: "20 hours",
      Connectivity: "Bluetooth 5.0",
    },
    inStock: true,
    featured: true,
  },
  {
    id: "h2",
    name: "Sony WH-1000XM5",
    brand: "Sony",
    category: "headphones",
    price: 349,
    originalPrice: 399,
    discount: 13,
    rating: 4.8,
    reviewCount: 4521,
    image: "https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=400&h=400&fit=crop",
    description: "Industry-leading noise cancellation with exceptional sound quality.",
    specifications: {
      Type: "Over-ear",
      "Noise Cancellation": "Dual Noise Sensor",
      Codec: "LDAC, AAC, SBC",
      Battery: "30 hours",
      Weight: "250g",
    },
    inStock: true,
    bestDeal: true,
  },
  {
    id: "h3",
    name: "Bose QuietComfort Ultra",
    brand: "Bose",
    category: "headphones",
    price: 429,
    originalPrice: 499,
    discount: 14,
    rating: 4.6,
    reviewCount: 1234,
    image: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=400&h=400&fit=crop",
    description: "Immersive audio with world-class quiet and spatial sound.",
    specifications: {
      Type: "Over-ear",
      "Noise Cancellation": "CustomTune technology",
      "Immersive Audio": "Bose Immersive Audio",
      Battery: "24 hours",
      Connectivity: "Bluetooth 5.3",
    },
    inStock: true,
    bestDeal: true,
  },
  {
    id: "h4",
    name: "AirPods Pro 2",
    brand: "Apple",
    category: "headphones",
    price: 249,
    rating: 4.7,
    reviewCount: 5678,
    image: "https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=400&h=400&fit=crop",
    description: "Pro-level Active Noise Cancellation and Adaptive Audio.",
    specifications: {
      Type: "In-ear",
      "Noise Cancellation": "Active Noise Cancellation",
      Chip: "H2",
      Battery: "6 hours (30 with case)",
      "Water Resistant": "IPX4",
    },
    inStock: true,
  },

  // Gaming
  {
    id: "g1",
    name: "PlayStation 5",
    brand: "Sony",
    category: "gaming",
    price: 499,
    rating: 4.9,
    reviewCount: 8765,
    image: "https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=400&h=400&fit=crop",
    description: "Experience lightning-fast loading, haptic feedback, and stunning 4K graphics.",
    specifications: {
      CPU: "AMD Zen 2, 8 cores",
      GPU: "AMD RDNA 2, 10.28 TFLOPs",
      Storage: "825GB SSD",
      Resolution: "Up to 4K 120fps",
      "Ray Tracing": "Hardware-accelerated",
    },
    inStock: true,
    featured: true,
  },
  {
    id: "g2",
    name: "Xbox Series X",
    brand: "Microsoft",
    category: "gaming",
    price: 499,
    originalPrice: 549,
    discount: 9,
    rating: 4.8,
    reviewCount: 6543,
    image: "https://images.unsplash.com/photo-1621259182978-fbf93132d53d?w=400&h=400&fit=crop",
    description: "The fastest, most powerful Xbox ever with 12 teraflops of gaming power.",
    specifications: {
      CPU: "AMD Zen 2, 8 cores",
      GPU: "AMD RDNA 2, 12 TFLOPs",
      Storage: "1TB SSD",
      Resolution: "Up to 4K 120fps",
      "Quick Resume": "Yes",
    },
    inStock: true,
    bestDeal: true,
  },
  {
    id: "g3",
    name: "Nintendo Switch OLED",
    brand: "Nintendo",
    category: "gaming",
    price: 349,
    rating: 4.7,
    reviewCount: 4321,
    image: "https://images.unsplash.com/photo-1578303512597-81e6cc155b3e?w=400&h=400&fit=crop",
    description: "Play at home or on the go with a vibrant 7-inch OLED screen.",
    specifications: {
      Display: '7" OLED',
      Storage: "64GB internal",
      "Play Modes": "TV, Tabletop, Handheld",
      Battery: "4.5-9 hours",
      "Online Play": "Nintendo Switch Online",
    },
    inStock: true,
    bestDeal: true,
  },
  {
    id: "g4",
    name: "Steam Deck OLED",
    brand: "Valve",
    category: "gaming",
    price: 549,
    rating: 4.6,
    reviewCount: 2345,
    image: "https://images.unsplash.com/photo-1640955014216-75201056c829?w=400&h=400&fit=crop",
    description: "Your Steam library in your hands with stunning HDR OLED display.",
    specifications: {
      Display: '7.4" HDR OLED',
      Processor: "AMD APU",
      Storage: "512GB NVMe SSD",
      Battery: "3-12 hours",
      OS: "SteamOS 3.0",
    },
    inStock: true,
  },

  // Accessories
  {
    id: "a1",
    name: "Apple Watch Ultra 2",
    brand: "Apple",
    category: "accessories",
    price: 799,
    rating: 4.8,
    reviewCount: 1876,
    image: "https://images.unsplash.com/photo-1434493789847-2f02dc6ca35d?w=400&h=400&fit=crop",
    description: "The most rugged and capable Apple Watch for extreme adventures.",
    specifications: {
      Display: '49mm Always-On Retina',
      Chip: "S9 SiP",
      "Water Resistant": "100m",
      Battery: "36 hours (72 in Low Power)",
      GPS: "Precision dual-frequency",
    },
    inStock: true,
    featured: true,
  },
  {
    id: "a2",
    name: "MagSafe Charger",
    brand: "Apple",
    category: "accessories",
    price: 39,
    rating: 4.5,
    reviewCount: 3456,
    image: "https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=400&h=400&fit=crop",
    description: "Perfectly aligned wireless charging for iPhone.",
    specifications: {
      Compatibility: "iPhone 12 and later",
      "Charging Speed": "Up to 15W",
      "Cable Length": "1m",
      Connector: "USB-C",
    },
    inStock: true,
  },
  {
    id: "a3",
    name: "Samsung T7 Shield 2TB",
    brand: "Samsung",
    category: "accessories",
    price: 189,
    originalPrice: 229,
    discount: 17,
    rating: 4.7,
    reviewCount: 2134,
    image: "https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=400&h=400&fit=crop",
    description: "Rugged portable SSD with incredible speed and durability.",
    specifications: {
      Capacity: "2TB",
      "Read Speed": "Up to 1,050 MB/s",
      Interface: "USB 3.2 Gen 2",
      Durability: "IP65 rated",
      Encryption: "256-bit AES",
    },
    inStock: true,
    bestDeal: true,
  },
  {
    id: "a4",
    name: "Logitech MX Master 3S",
    brand: "Logitech",
    category: "accessories",
    price: 99,
    rating: 4.8,
    reviewCount: 4567,
    image: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400&h=400&fit=crop",
    description: "Advanced wireless mouse with ultra-fast scrolling.",
    specifications: {
      Sensor: "8K DPI optical",
      Buttons: "7 programmable",
      Battery: "70 days",
      Connectivity: "Bluetooth + USB receiver",
      "Multi-device": "Up to 3 devices",
    },
    inStock: true,
  },
];

// Helper functions
export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}

export function getProductsByCategory(category: Category): Product[] {
  return products.filter((p) => p.category === category);
}

export function getFeaturedProducts(): Product[] {
  return products.filter((p) => p.featured);
}

export function getBestDeals(): Product[] {
  return products.filter((p) => p.bestDeal);
}

export function getAllBrands(): string[] {
  return [...new Set(products.map((p) => p.brand))];
}

export function searchProducts(query: string): Product[] {
  const lowercaseQuery = query.toLowerCase();
  return products.filter(
    (p) =>
      p.name.toLowerCase().includes(lowercaseQuery) ||
      p.brand.toLowerCase().includes(lowercaseQuery) ||
      p.description.toLowerCase().includes(lowercaseQuery)
  );
}
